# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('t3guard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='config_type',
            field=models.CharField(choices=[(b'ALARM', b'Alarm-Type'), (b'EMAIL', b'Email address'), (b'RADIO', b'Radio'), (b'CHECKER', b'Configuration for checker.py')], max_length=10),
        ),
    ]
